#!/usr/bin/env bash

# Update the package list to make sure you have the latest version
apt-get -y update

# Install nginx
apt-get -y install nginx

# Create a symbolic link for default configuration
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled

# Replace the default server block content with the required configuration
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    location / {
        echo 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Restart nginx without using systemctl
service nginx restart

# Ensure that nginx is running
if (( $(ps -ef | grep -v grep | grep nginx | wc -l) > 0 )); then
    echo "Nginx is running."
else
    echo "Nginx is not running. Check logs for errors."
fi
