#!/usr/bin/env bash
# a Bash script that displays listening ports
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"

# Get listening sockets information using theZZ 'ss' command
# '-l' option shows only listening sockets
# '-t' option shows TCP sockets
# '-p' option shows process information
ss -ltnp | awk 'NR>1 {print $1, $2, $3, $4, $5, $6}'

echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"

# Get UNIX domain listening sockets information using the 'ss' command
# '-l' option shows only listening sockets
# '-x' option shows UNIX domain sockets
# '-p' option shows process information
ss -lxnp | awk 'NR>1 {print $1, $2, $3, $4, $5, $6, $7}'
