#!/usr/bin/env bash
# Using an until loop to display "Best School" 10 times

# Initialize a counter variable
counter=0

until [ $counter -eq 10 ]
do
    echo "Best School"
    
    # Increment the counter
    ((counter++))
done
