#!/usr/bin/env bash
# display the content of the current directory In a list format

for file in *; do
    # Check if the file is not hidden and is a regular file (not a directory, etc.)
    if [[ ! "$file" =~ ^\..* ]] && [ -f "$file" ]; then
        # Extract the part of the name after the first dash
        name_after_dash="${file#*-}"
        echo "$name_after_dash"
    fi
done
