#!/bin/env bash

# Get all active IPv4 addresses using the 'ip' command
# Filter the output to display only IPv4 addresses
# Extract the IP addresses using 'awk'
ip -4 addr | grep -oP 'inet \K[\d.]+'
